# fly.toml app configuration file generated for sigle-image-embed on 2023-06-25T17:35:57+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sigle-image-embed"
primary_region = "sjc"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
